before:
  hooks:
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  -
    binary: go-njmvc-appointment
    main: ./njmvc.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: 386